/*
 * To change this license header, choose License Headers in Project Properties. * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/** *
 * @author raqibmuktadir
 */
import java.awt.event.*;
import java.awt.*;
import java.sql.*;
import javax.swing.*;
public class Reprographicsdata extends javax.swing.JFrame {
    /**
     * Creates new form Reprographicsdata */
    public Reprographicsdata() {
        initComponents(); }
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,
                WindowEvent.WINDOW_CLOSING); Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always * regenerated by the Form Editor.
 */
    @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code"> private void initComponents() {
    jScrollPane1 = new javax.swing.JScrollPane(); Table_MainMenu = new javax.swing.JTable(); jPanel3 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    inventory_menu = new javax.swing.JButton(); Printing_Photocopy_menu = new javax.swing.JButton(); issuing_history_menu = new javax.swing.JButton(); User_details = new javax.swing.JButton();
    cmd_exit = new javax.swing.JButton(); cmd_logout = new javax.swing.JButton(); jButton1 = new javax.swing.JButton();
Table_MainMenu.setModel(new javax.swing.table.DefaultTableModel( new Object [][] {
    },
            new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4" }
)); jScrollPane1.setViewportView(Table_MainMenu);
    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3); jPanel3.setLayout(jPanel3Layout);

jPanel3Layout.setHorizontalGroup( jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) .addGap(0, 466, Short.MAX_VALUE)
); jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE) );
jLabel2.setText("jLabel2");
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
jPanel1.setBackground(new java.awt.Color(204, 255, 255));
jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uwc-logo.png"))); // NOI18N
    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1); jPanel1.setLayout(jPanel1Layout);
jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) .addGroup(jPanel1Layout.createSequentialGroup()
.addGap(400, 400, 400) .addComponent(jLabel1) .addGap(400, 400, 400))
            ); jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) .addGroup(jPanel1Layout.createSequentialGroup()
.addContainerGap() .addComponent(jLabel1) .addGap(23, 23, 23))
            );
inventory_menu.setText("Inventory"); inventory_menu.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) { inventory_menuActionPerformed(evt);
        } });
Printing_Photocopy_menu.setText("Printing and Photocopy"); Printing_Photocopy_menu.addActionListener(new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) { Printing_Photocopy_menuActionPerformed(evt);
        } });
issuing_history_menu.setText("Issuing History"); issuing_history_menu.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) { issuing_history_menuActionPerformed(evt);
        } });
User_details.setText("User Details"); User_details.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) { User_detailsActionPerformed(evt);
        } });
cmd_exit.setText("EXIT");
cmd_exit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) { cmd_exitActionPerformed(evt);
        } });
cmd_logout.setText("LOG OUT"); cmd_logout.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) { cmd_logoutActionPerformed(evt);
        } });
jButton1.setText("Courier");
jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) { jButton1ActionPerformed(evt);
        } });
    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2); jPanel2.setLayout(jPanel2Layout);
jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel2Layout.createSequentialGroup() .addGap(20, 20, 20)
.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING) .addGroup(jPanel2Layout.createSequentialGroup()
.addComponent(inventory_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(20, 20, 20) .addComponent(Printing_Photocopy_menu) .addGap(20, 20, 20) .addComponent(issuing_history_menu,
                                                                                             javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)) .addGroup(jPanel2Layout.createSequentialGroup()
.addComponent(cmd_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(cmd_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(20, 20, 20)
.addComponent(User_details, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(20, 20, 20)
.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(20, 20, 20)) );
jPanel2Layout.setVerticalGroup( jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) .addGroup(jPanel2Layout.createSequentialGroup()
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) .addComponent(issuing_history_menu, javax.swing.GroupLayout.PREFERRED_SIZE,
60, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(inventory_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
              javax.swing.GroupLayout.PREFERRED_SIZE) .addComponent(Printing_Photocopy_menu,
                                                                    javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE) .addComponent(User_details, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                                                                                                                                                      javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
              javax.swing.GroupLayout.PREFERRED_SIZE)) .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58,
                                                                        Short.MAX_VALUE)

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) .addComponent(cmd_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                                                                                      javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(cmd_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
              javax.swing.GroupLayout.PREFERRED_SIZE)) .addContainerGap(18, Short.MAX_VALUE))
            );
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane()); getContentPane().setLayout(layout);
layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addGroup(layout.createSequentialGroup()
.addGap(40, 40, 40)
.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) .addGap(40, 40, 40))
            ); layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) .addGroup(layout.createSequentialGroup()
.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(122, 122, 122)
.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addContainerGap(75, Short.MAX_VALUE)) );
    pack();
}// </editor-fold>
    private void Printing_Photocopy_menuActionPerformed(java.awt.event.ActionEvent evt) { Printing_and_Photocopy a =new Printing_and_Photocopy();
        a.setVisible(true);
        close();
    }
    private void inventory_menuActionPerformed(java.awt.event.ActionEvent evt) { Inventory a =new Inventory();
        a.setVisible(true);

        close(); }
    private void issuing_history_menuActionPerformed(java.awt.event.ActionEvent evt) { Issuing_History a =new Issuing_History();
        a.setVisible(true);
        close();
    }
    private void User_detailsActionPerformed(java.awt.event.ActionEvent evt) { UserDetails a =new UserDetails();
        a.setVisible(true);
        close();
    }
    private void cmd_exitActionPerformed(java.awt.event.ActionEvent evt) { System.exit(0);
    }
    private void cmd_logoutActionPerformed(java.awt.event.ActionEvent evt) { Loginpage a =new Loginpage();
        a.setVisible(true);
        close();// TODO add your handling code here:
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { Courier a =new Courier();
        a.setVisible(true);
        close();// TODO add your handling code here:
    }
    /**
     * @param args the command line arguments */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) "> /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
*/ try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) { javax.swing.UIManager.setLookAndFeel(info.getClassName()); break;
                } }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reprographicsdata.class.getName()).log(java.util.logging.Leve l.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reprographicsdata.class.getName()).log(java.util.logging.Leve l.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reprographicsdata.class.getName()).log(java.util.logging.Leve l.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reprographicsdata.class.getName()).log(java.util.logging.Leve l.SEVERE, null, ex);
        } //</editor-fold>
        /* Create and display the form */ java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reprographicsdata().setVisible(true);
            } });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton Printing_Photocopy_menu; private javax.swing.JTable Table_MainMenu;
    private javax.swing.JButton User_details;
    private javax.swing.JButton cmd_exit;
    private javax.swing.JButton cmd_logout;
    private javax.swing.JButton inventory_menu;
    private javax.swing.JButton issuing_history_menu; private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1; // End of variables declaration
}