import java.awt.event.*;
import java.awt.*;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils; import java.text.*;
import java.io.File;
/*
 * To change this license header, choose License Headers in Project Properties. * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/** *
 * @author raqibmuktadir
 */
public class UserDetails extends javax.swing.JFrame {
    Connection conn=null; ResultSet rs=null; PreparedStatement pst=null; /**
     * Creates new form UserDetails
     */
    public UserDetails() {
        initComponents(); conn=javaconnect.ConnecrDb(); Update_table();
    }
    public void Update_table(){
        try{
            String sql= "select * from UserDetails"; pst=conn.prepareStatement(sql);
            rs=pst.executeQuery(); Table_UserDetails.setModel(DbUtils.resultSetToTableModel(rs)); }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } finally{
            try{ rs.close(); pst.close();
            }
            catch(Exception e){ }
        } }
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,
                WindowEvent.WINDOW_CLOSING); Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always * regenerated by the Form Editor.
 */
    @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code"> private void initComponents() {
    jPanel4 = new javax.swing.JPanel(); cmd_attach = new javax.swing.JButton(); txt_filechooser = new javax.swing.JTextField(); jScrollPane1 = new javax.swing.JScrollPane(); Table_UserDetails = new javax.swing.JTable(); jPanel2 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    txt_id = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel(); txt_username = new javax.swing.JTextField();

    cmd_delete = new javax.swing.JButton(); txt_password = new javax.swing.JTextField(); txt_adminornot = new javax.swing.JTextField(); cmd_save = new javax.swing.JButton(); cmd_update = new javax.swing.JButton(); jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    back = new javax.swing.JButton(); cmd_clear = new javax.swing.JButton(); cmd_print = new javax.swing.JButton(); jLabel6 = new javax.swing.JLabel(); txt_name = new javax.swing.JTextField(); jPanel3 = new javax.swing.JPanel(); txt_search = new javax.swing.JTextField(); jPanel1 = new javax.swing.JPanel(); jLabel1 = new javax.swing.JLabel();
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "File Chooser", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 18))); // NOI18N
cmd_attach.setText("Attach");
cmd_attach.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) { cmd_attachActionPerformed(evt);
        } });
    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4); jPanel4.setLayout(jPanel4Layout);
jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) .addGroup(jPanel4Layout.createSequentialGroup()
.addContainerGap()
.addComponent(txt_filechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) .addComponent(cmd_attach) .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            ); jPanel4Layout.setVerticalGroup(

            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) .addGroup(jPanel4Layout.createSequentialGroup()
.addContainerGap()
.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) .addComponent(txt_filechooser, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                      javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) .addComponent(cmd_attach))
            .addContainerGap()) );
Table_UserDetails.setModel(new javax.swing.table.DefaultTableModel( new Object [][] {
    },
            new String [] {
        "Product ID", "Item Name", "Type of Item", "Units in Inventory" }
));
Table_UserDetails.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) { Table_UserDetailsMouseClicked(evt);
        } });
Table_UserDetails.addKeyListener(new java.awt.event.KeyAdapter() { public void keyPressed(java.awt.event.KeyEvent evt) {
        Table_UserDetailsKeyPressed(evt); }
    }); jScrollPane1.setViewportView(Table_UserDetails);
jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 18))); // NOI18N
jLabel4.setText("Password"); jLabel5.setText("Admin or Not");
cmd_delete.setText("Delete");
cmd_delete.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) { cmd_deleteActionPerformed(evt);

        } });
cmd_save.setText("Save");
cmd_save.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) { cmd_saveActionPerformed(evt);
        } });
cmd_update.setText("Update");
cmd_update.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) { cmd_updateActionPerformed(evt);
        } });
jLabel2.setText("ID"); jLabel3.setText("Username");
back.setText("Back to Main Menu"); back.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) { backActionPerformed(evt);
        } });
cmd_clear.setText("Clear");
cmd_clear.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) { cmd_clearActionPerformed(evt);
        } });
cmd_print.setText("Print");
cmd_print.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) { cmd_printActionPerformed(evt);
        } });
jLabel6.setText("Name");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2); jPanel2.setLayout(jPanel2Layout);
jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) .addGroup(jPanel2Layout.createSequentialGroup()
.addContainerGap()
.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) .addGroup(jPanel2Layout.createSequentialGroup()
.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) .addGroup(jPanel2Layout.createSequentialGroup()
.addComponent(cmd_update) .addGap(20, 20, 20) .addComponent(cmd_save) .addGap(20, 20, 20) .addComponent(cmd_delete) .addGap(20, 20, 20) .addComponent(cmd_clear))
            .addGroup(jPanel2Layout.createSequentialGroup() .addGap(41, 41, 41)
.addComponent(back)
.addGap(18, 18, 18) .addComponent(cmd_print)))
            .addGap(0, 100, Short.MAX_VALUE)) .addGroup(jPanel2Layout.createSequentialGroup()
.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) .addComponent(jLabel2)
.addComponent(jLabel3) .addComponent(jLabel4) .addComponent(jLabel5) .addComponent(jLabel6))
            .addGap(49, 49, 49)
.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) .addComponent(txt_name)
.addComponent(txt_id, javax.swing.GroupLayout.Alignment.TRAILING) .addComponent(txt_username, javax.swing.GroupLayout.Alignment.TRAILING) .addComponent(txt_password, javax.swing.GroupLayout.Alignment.TRAILING) .addComponent(txt_adminornot,
                                                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)))) .addContainerGap())
            );

jPanel2Layout.setVerticalGroup( jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) .addGroup(jPanel2Layout.createSequentialGroup()
.addContainerGap()
.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) .addComponent(jLabel2)
.addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(20, 20, 20)
.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                      javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) .addComponent(jLabel3))
            .addGap(21, 21, 21)
.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addComponent(txt_password)
.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) .addComponent(txt_adminornot, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                      javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) .addComponent(jLabel5))
            .addGap(20, 20, 20)
.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                      javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) .addComponent(jLabel6))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) .addComponent(cmd_update)
.addComponent(cmd_delete) .addComponent(cmd_save) .addComponent(cmd_clear))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) .addComponent(back)
.addComponent(cmd_print))) );
jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 18))); // NOI18N
txt_search.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) {
        txt_searchActionPerformed(evt); }
    });
txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) { txt_searchKeyReleased(evt);
        } });
    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3); jPanel3.setLayout(jPanel3Layout);
jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) .addGroup(jPanel3Layout.createSequentialGroup()
.addContainerGap()
.addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
.addContainerGap()) );
jPanel3Layout.setVerticalGroup( jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) .addGroup(jPanel3Layout.createSequentialGroup()
.addContainerGap()
.addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addContainerGap()) );
jPanel1.setBackground(new java.awt.Color(204, 255, 255));

jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uwc-logo.png"))); // NOI18N
    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1); jPanel1.setLayout(jPanel1Layout);
jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) .addGroup(jPanel1Layout.createSequentialGroup()
.addGap(550, 550, 550) .addComponent(jLabel1) .addGap(550, 550, 550))
            ); jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
.addContainerGap()
.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addContainerGap()) );
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane()); getContentPane().setLayout(layout);
layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addContainerGap() .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(18, 18, 18)
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
.addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                          Short.MAX_VALUE)

); layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addGap(0, 0, Short.MAX_VALUE)
.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) .addGroup(layout.createSequentialGroup()
.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            );
    pack();
}// </editor-fold>
    private void cmd_attachActionPerformed(java.awt.event.ActionEvent evt) { JFileChooser chooser= new JFileChooser(); chooser.showOpenDialog(null);
        File f =chooser.getSelectedFile();
        String filename =f.getAbsolutePath();
        txt_filechooser.setText(filename); }
    private void Table_UserDetailsMouseClicked(java.awt.event.MouseEvent evt) { try{
        int row = Table_UserDetails.getSelectedRow();
        String Table_click= (Table_UserDetails.getModel().getValueAt(row, 0).toString()); String sql ="select * from UserDetails where Id='"+Table_click+"'"; pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        if(rs.next()){
            String add1=rs.getString("Id"); txt_id.setText(add1);
            String add2=rs.getString("Username");

            txt_username.setText(add2);
            String add3=rs.getString("Password"); txt_password.setText(add3);
            String add4=rs.getString("admin_or_not"); txt_adminornot.setText(add4);
            String add5=rs.getString("Name"); txt_name.setText(add5);
        } }
    catch(Exception e){ JOptionPane.showMessageDialog(null, e);
    } finally{ try{
        rs.close();
        pst.close(); }
    catch(Exception e){
    } }
    }
    private void Table_UserDetailsKeyPressed(java.awt.event.KeyEvent evt) { if(evt.getKeyCode()==KeyEvent.VK_DOWN || evt.getKeyCode()==KeyEvent.VK_UP){
        try{
            int row = Table_UserDetails.getSelectedRow();
            String Table_click= (Table_UserDetails.getModel().getValueAt(row, 0).toString()); String sql ="select * from UserDetails where Id='"+Table_click+"'"; pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("Id"); txt_id.setText(add1);
                String add2=rs.getString("Username"); txt_username.setText(add2);
                String add3=rs.getString("Password"); txt_password.setText(add3);
                String add4=rs.getString("admin_or_not"); txt_adminornot.setText(add4);
                String add5=rs.getString("Name"); txt_name.setText(add5);
            } }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e); } finally{
            try{ rs.close(); pst.close();
            }
            catch(Exception e){ }
        } }
    }
    private void cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) { String sql= "delete from UserDetails where Id=?";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1, txt_id.getText());
            pst.execute(); JOptionPane.showMessageDialog(null, "Deleted");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e); }
        Update_table(); }
    private void cmd_saveActionPerformed(java.awt.event.ActionEvent evt) { try{
        String sql= "Insert into UserDetails (Id,Username,Password,admin_or_not,Name) values (?,?,?,?,?)";
        pst=conn.prepareStatement(sql); pst.setString(1, txt_id.getText());
        pst.setString(2, txt_username.getText()); pst.setString(3, txt_password.getText()); pst.setString(4, txt_adminornot.getText()); pst.setString(5, txt_name.getText()); pst.execute(); JOptionPane.showMessageDialog(null, "Saved");
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e); }
        Update_table(); }

    private void cmd_updateActionPerformed(java.awt.event.ActionEvent evt) { try{
        String value1 = txt_id.getText();
        String value2 = txt_username.getText();
        String value3 = txt_password.getText();
        String value4 = txt_adminornot.getText();
        String value5 = txt_name.getText();
        String sql= "update UserDetails set Id='"+value1+"' ,Username='"+value2+"'
                ,Password='"+value3+"' ,admin_or_not='"+value4+"', Name='"+value5+"' where Id='"+value1+"'";
        pst=conn.prepareStatement(sql);
        pst.execute(); JOptionPane.showMessageDialog(null, "Updated");
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e); }
        Update_table(); }
    private void backActionPerformed(java.awt.event.ActionEvent evt) { Reprographicsdata a =new Reprographicsdata(); a.setVisible(true);
        close();
    }
    private void cmd_clearActionPerformed(java.awt.event.ActionEvent evt) { txt_id.setText("");
        txt_username.setText("");
        txt_password.setText("");
        txt_adminornot.setText("");
        txt_name.setText(""); }
    private void cmd_printActionPerformed(java.awt.event.ActionEvent evt) { MessageFormat header= new MessageFormat("User Details Report"); MessageFormat footer= new MessageFormat("Page{0,number,integer}"); try{
        Table_UserDetails.print(JTable.PrintMode.NORMAL, header, footer); }
    catch(java.awt.print.PrinterException e){ System.err.format("Cannot print", e.getMessage());
    }

    }
    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) { // TODO add your handling code here:
    }
    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) { try{
        String sql= "select * from UserDetails where Name=?"; pst=conn.prepareStatement(sql);
        pst.setString(1, txt_search.getText()); rs=pst.executeQuery();
        if(rs.next()){
            String add1=rs.getString("Id"); txt_id.setText(add1);
            String add2=rs.getString("Username"); txt_username.setText(add2);
            String add3=rs.getString("Password"); txt_password.setText(add3);
            String add4=rs.getString("admin_or_not"); txt_adminornot.setText(add4);
            String add5=rs.getString("Name"); txt_name.setText(add5);
        } }
    catch(Exception e){ JOptionPane.showMessageDialog(null, e);
    }finally{ try{
        rs.close();
        pst.close(); }
    catch(Exception e){
    } }
        try{
            String sql= "select * from UserDetails where Id=?"; pst=conn.prepareStatement(sql);
            pst.setString(1, txt_search.getText()); rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("Id"); txt_id.setText(add1);

                String add2=rs.getString("Username"); txt_username.setText(add2);
                String add3=rs.getString("Password"); txt_password.setText(add3);
                String add4=rs.getString("admin_or_not"); txt_adminornot.setText(add4);
                String add5=rs.getString("Name"); txt_name.setText(add5);
            } }
        catch(Exception e){ JOptionPane.showMessageDialog(null, e);
        }finally{ try{
            rs.close();
            pst.close(); }
        catch(Exception e){
        } }
        try{
            String sql= "select * from UserDetails where Username=?"; pst=conn.prepareStatement(sql);
            pst.setString(1, txt_search.getText()); rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("Id"); txt_id.setText(add1);
                String add2=rs.getString("Username"); txt_username.setText(add2);
                String add3=rs.getString("Password"); txt_password.setText(add3);
                String add4=rs.getString("admin_or_not"); txt_adminornot.setText(add4);
                String add5=rs.getString("Name"); txt_name.setText(add5);
            } }
        catch(Exception e){ JOptionPane.showMessageDialog(null, e);
        }finally{ try{
            rs.close();

            pst.close(); }
        catch(Exception e){
        } }
        try{
            String sql= "select * from UserDetails where Password=?"; pst=conn.prepareStatement(sql);
            pst.setString(1, txt_search.getText()); rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("Id"); txt_id.setText(add1);
                String add2=rs.getString("Username"); txt_username.setText(add2);
                String add3=rs.getString("Password"); txt_password.setText(add3);
                String add4=rs.getString("admin_or_not"); txt_adminornot.setText(add4);
                String add5=rs.getString("Name"); txt_name.setText(add5);
            } }
        catch(Exception e){ JOptionPane.showMessageDialog(null, e);
        }finally{ try{
            rs.close();
            pst.close(); }
        catch(Exception e){
        } }
        try{
            String sql= "select * from UserDetails where admin_or_not=?"; pst=conn.prepareStatement(sql);
            pst.setString(1, txt_search.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("Id"); txt_id.setText(add1);
                String add2=rs.getString("Username");

                txt_username.setText(add2);
                String add3=rs.getString("Password"); txt_password.setText(add3);
                String add4=rs.getString("admin_or_not"); txt_adminornot.setText(add4);
                String add5=rs.getString("Name"); txt_name.setText(add5);
            } }
        catch(Exception e){ JOptionPane.showMessageDialog(null, e);
        }finally{ try{
            rs.close();
            pst.close(); }
        catch(Exception e){
        } }
    }
    /**
     * @param args the command line arguments */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) "> /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
*/ try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) { javax.swing.UIManager.setLookAndFeel(info.getClassName()); break;
                } }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVE RE, null, ex);
        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVE RE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVE RE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVE RE, null, ex);
        } //</editor-fold>
        /* Create and display the form */ java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDetails().setVisible(true);
            } });
    }
    // Variables declaration - do not modify private javax.swing.JTable Table_UserDetails; private javax.swing.JButton back;
    private javax.swing.JButton cmd_attach; private javax.swing.JButton cmd_clear;
    private javax.swing.JButton cmd_delete; private javax.swing.JButton cmd_print;
    private javax.swing.JButton cmd_save;
    private javax.swing.JButton cmd_update; private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1; private javax.swing.JTextField txt_adminornot; private javax.swing.JTextField txt_filechooser;

    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name; private javax.swing.JTextField txt_password; private javax.swing.JTextField txt_search; private javax.swing.JTextField txt_username; // End of variables declaration
}
